#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook "apt"
cookbook "build-essential",
	:git => "https://github.com/opscode-cookbooks/build-essential.git"
cookbook 'postgresql',
  :git => 'https://github.com/hw-cookbooks/postgresql.git'
